name: Hello-GitHub-Actions

on:
  workflow_dispatch: # 수동 실행 버튼 활성화
    inputs:
      user_name:
        description: '이름을 입력하세요'
        required: true
        default: 'GitHub-User22'

jobs:
  say-hello:
    runs-on: ubuntu-latest # GitHub에서 제공하는 가상 머신 사용
    steps:
      - name: Greet user
        run: |
          echo "안녕하세요, ${{ github.event.inputs.user_name }}님!"
          echo "GitHub Actions가 성공적으로 실행되었습니다."
